import { FiltroEstado, FiltroEtapa, FiltroMarca } from 'src/models/filtros/Filtro';

export const MARCAS: FiltroMarca[] = [
  { id: 1, text: 'MASTERCARD', selected: false },
  { id: 2, text: 'VISA', selected: false },
];

export const ETAPAS: FiltroEtapa[] = [
  { id: 1, idMarca: 1, text: "Recepcion", selected: false },
  { id: 2, idMarca: 1, text: "Contracargo", selected: false },
  { id: 3, idMarca: 1, text: "Disputa", selected: false },
  { id: 4, idMarca: 1, text: "Pre-arbitraje", selected: false },
  { id: 5, idMarca: 1, text: "Arbitraje", selected: false },
  { id: 6, idMarca: 1, text: "Resolucion", selected: false },
  { id: 7, idMarca: 1, text: "Apelacion", selected: false },
  { id: 8, idMarca: 1, text: "Recepcion", selected: false },
  { id: 9, idMarca: 2, text: "Contracargo", selected: false },
  { id: 10, idMarca: 2, text: "Pre-arbitraje", selected: false },
  { id: 11, idMarca: 2, text: "Arbitraje", selected: false },
  { id: 12, idMarca: 2, text: "Resolucion", selected: false },
  { id: 13, idMarca: 2, text: "Apelacion", selected: false }
];

export const ESTADOS: FiltroEstado[] = [
  { id: 1, idEtapa: 2, idMarca: 1, text: "Recibido", selected: false },
  { id: 2, idEtapa: 2, idMarca: 1, text: "Motivo No Encontrado", selected: false },
  { id: 3, idEtapa: 2, idMarca: 1, text: "Motivo Por Aprobar", selected: false },
  { id: 4, idEtapa: 2, idMarca: 1, text: "Motivo Aprobado", selected: false },
  { id: 5, idEtapa: 2, idMarca: 1, text: "Por Gestionar", selected: false },
  { id: 6, idEtapa: 2, idMarca: 1, text: "Cierre Programado", selected: false },
  { id: 7, idEtapa: 2, idMarca: 1, text: "Cerrado", selected: false },
  { id: 8, idEtapa: 2, idMarca: 1, text: "Notificacion Programada", selected: false },
  { id: 9, idEtapa: 2, idMarca: 1, text: "Rechazado", selected: false },
  { id: 10, idEtapa: 2, idMarca: 1, text: "Por Aceptar", selected: false },
  { id: 11, idEtapa: 2, idMarca: 1, text: "Aceptado", selected: false },
  { id: 12, idEtapa: 2, idMarca: 1, text: "Notificado", selected: false },
  { id: 13, idEtapa: 2, idMarca: 1, text: "Debito Programado", selected: false },
  { id: 14, idEtapa: 2, idMarca: 1, text: "Debitado", selected: false },
  { id: 15, idEtapa: 9, idMarca: 2, text: "Recibido", selected: false },
  { id: 16, idEtapa: 9, idMarca: 2, text: "Motivo No Encontrado", selected: false },
  { id: 17, idEtapa: 9, idMarca: 2, text: "Motivo Por Aprobar", selected: false },
  { id: 18, idEtapa: 9, idMarca: 2, text: "Motivo Aprobado", selected: false },
  { id: 19, idEtapa: 9, idMarca: 2, text: "Por Gestionar", selected: false },
  { id: 20, idEtapa: 9, idMarca: 2, text: "Cierre Programado", selected: false },
  { id: 21, idEtapa: 9, idMarca: 2, text: "Cerrado", selected: false },
  { id: 22, idEtapa: 9, idMarca: 2, text: "Notificacion Programada", selected: false },
  { id: 23, idEtapa: 9, idMarca: 2, text: "Rechazado", selected: false },
  { id: 24, idEtapa: 9, idMarca: 2, text: "Por Aceptar", selected: false },
  { id: 25, idEtapa: 9, idMarca: 2, text: "Aceptado", selected: false },
  { id: 26, idEtapa: 9, idMarca: 2, text: "Notificado", selected: false },
  { id: 27, idEtapa: 9, idMarca: 2, text: "Debito Programado", selected: false },
  { id: 28, idEtapa: 9, idMarca: 2, text: "Debitado", selected: false },
  { id: 29, idEtapa: 2, idMarca: 1, text: "No Gestionado/Aceptado", selected: false },
  { id: 30, idEtapa: 3, idMarca: 1, text: "Disputado", selected: false },
  { id: 31, idEtapa: 3, idMarca: 1, text: "Ganada", selected: false },
  { id: 32, idEtapa: 4, idMarca: 1, text: "Notificado", selected: false },
  { id: 33, idEtapa: 4, idMarca: 1, text: "No Gestionado/Aceptado", selected: false },
  { id: 34, idEtapa: 4, idMarca: 1, text: "Aceptado", selected: false },
  { id: 35, idEtapa: 4, idMarca: 1, text: "Cerrado", selected: false },
  { id: 36, idEtapa: 4, idMarca: 1, text: "Pre-Arbitrado", selected: false },
  { id: 37, idEtapa: 4, idMarca: 1, text: "Ganado", selected: false },
  { id: 38, idEtapa: 9, idMarca: 2, text: "No Gestionado/Aceptado", selected: false },
  { id: 39, idEtapa: 10, idMarca: 2, text: "Pre-Arbitrado", selected: false },
  { id: 40, idEtapa: 10, idMarca: 2, text: "Ganado", selected: false },
  { id: 41, idEtapa: 11, idMarca: 2, text: "Notificado", selected: false },
  { id: 42, idEtapa: 11, idMarca: 2, text: "No Gestionado/Aceptado", selected: false },
  { id: 43, idEtapa: 11, idMarca: 2, text: "Aceptado", selected: false },
  { id: 44, idEtapa: 11, idMarca: 2, text: "Cerrado", selected: false },
  { id: 45, idEtapa: 11, idMarca: 2, text: "Arbitrado", selected: false },
  { id: 46, idEtapa: 11, idMarca: 2, text: "Ganado", selected: false },
  { id: 47, idEtapa: 11, idMarca: 2, text: "Perdido", selected: false },
  { id: 48, idEtapa: 5, idMarca: 1, text: "Abonado", selected: false },
  { id: 49, idEtapa: 5, idMarca: 1, text: "Abono Programado", selected: false },
  { id: 50, idEtapa: 5, idMarca: 1, text: "Aceptado", selected: false },
  { id: 51, idEtapa: 5, idMarca: 1, text: "Arbitrado", selected: false },
  { id: 52, idEtapa: 5, idMarca: 1, text: "Cerrado", selected: false },
  { id: 53, idEtapa: 5, idMarca: 1, text: "Configurado", selected: false },
  { id: 54, idEtapa: 5, idMarca: 1, text: "Debitado", selected: false },
  { id: 55, idEtapa: 5, idMarca: 1, text: "Debito Programado", selected: false },
  { id: 56, idEtapa: 5, idMarca: 1, text: "Evidencia Rechazada", selected: false },
  { id: 57, idEtapa: 5, idMarca: 1, text: "Ganado", selected: false },
  { id: 58, idEtapa: 5, idMarca: 1, text: "No Gestionado/Aceptado", selected: false },
  { id: 59, idEtapa: 5, idMarca: 1, text: "Notificacion Programada", selected: false },
  { id: 60, idEtapa: 5, idMarca: 1, text: "Notificado", selected: false },
  { id: 61, idEtapa: 5, idMarca: 1, text: "Perdido", selected: false },
  { id: 62, idEtapa: 5, idMarca: 1, text: "Perdido", selected: false },
  { id: 63, idEtapa: 5, idMarca: 1, text: "Por Abonar", selected: false },
  { id: 64, idEtapa: 5, idMarca: 1, text: "Por Aceptar", selected: false },
  { id: 65, idEtapa: 5, idMarca: 1, text: "Por Arbitar", selected: false },
  { id: 66, idEtapa: 5, idMarca: 1, text: "Por Gestionar", selected: false },
  { id: 67, idEtapa: 5, idMarca: 1, text: "Programado", selected: false },
  { id: 68, idEtapa: 5, idMarca: 1, text: "Rechazado", selected: false },
  { id: 69, idEtapa: 5, idMarca: 1, text: "Resuelto", selected: false },
  { id: 70, idEtapa: 2, idMarca: 1, text: "Notificado", selected: false },
  { id: 71, idEtapa: 3, idMarca: 1, text: "Abonado", selected: false },
  { id: 72, idEtapa: 3, idMarca: 1, text: "Abono Programado", selected: false },
  { id: 73, idEtapa: 3, idMarca: 1, text: "Cerrada", selected: false },
  { id: 74, idEtapa: 3, idMarca: 1, text: "Cierre Programado", selected: false },
  { id: 75, idEtapa: 3, idMarca: 1, text: "Configurada", selected: false },
  { id: 76, idEtapa: 3, idMarca: 1, text: "Evidencia Rechazada", selected: false },
  { id: 77, idEtapa: 3, idMarca: 1, text: "Por Abonar", selected: false },
  { id: 78, idEtapa: 3, idMarca: 1, text: "Por Disputar", selected: false },
  { id: 79, idEtapa: 3, idMarca: 1, text: "Programada", selected: false },
  { id: 80, idEtapa: 3, idMarca: 1, text: "Rechazada", selected: false },
  { id: 81, idEtapa: 4, idMarca: 1, text: "Abonado", selected: false },
  { id: 82, idEtapa: 4, idMarca: 1, text: "Abono Programado", selected: false },
  { id: 83, idEtapa: 4, idMarca: 1, text: "Cierre Programado", selected: false },
  { id: 84, idEtapa: 4, idMarca: 1, text: "Configurado", selected: false },
  { id: 85, idEtapa: 4, idMarca: 1, text: "Debitado", selected: false },
  { id: 86, idEtapa: 4, idMarca: 1, text: "Debito Programado", selected: false },
  { id: 87, idEtapa: 4, idMarca: 1, text: "Evidencia Rechazada", selected: false },
  { id: 88, idEtapa: 4, idMarca: 1, text: "Notificacion Programada", selected: false },
  { id: 89, idEtapa: 4, idMarca: 1, text: "Por Abonar", selected: false },
  { id: 90, idEtapa: 4, idMarca: 1, text: "Por Aceptar", selected: false },
  { id: 91, idEtapa: 4, idMarca: 1, text: "Por Gestionar", selected: false },
  { id: 92, idEtapa: 4, idMarca: 1, text: "Por Pre-Arbitrar", selected: false },
  { id: 93, idEtapa: 4, idMarca: 1, text: "Programado", selected: false },
  { id: 94, idEtapa: 4, idMarca: 1, text: "Rechazado", selected: false },
  { id: 95, idEtapa: 11, idMarca: 2, text: "Abonado", selected: false },
  { id: 96, idEtapa: 11, idMarca: 2, text: "Abono Programado", selected: false },
  { id: 97, idEtapa: 11, idMarca: 2, text: "Configurado", selected: false },
  { id: 98, idEtapa: 11, idMarca: 2, text: "Debitado", selected: false },
  { id: 99, idEtapa: 11, idMarca: 2, text: "Debito Programado", selected: false },
  { id: 100, idEtapa: 11, idMarca: 2, text: "Evidencia Rechazada", selected: false },
  { id: 101, idEtapa: 11, idMarca: 2, text: "Notificacion Programada", selected: false },
  { id: 102, idEtapa: 11, idMarca: 2, text: "Perdido", selected: false },
  { id: 103, idEtapa: 11, idMarca: 2, text: "Por Abonar", selected: false },
  { id: 104, idEtapa: 11, idMarca: 2, text: "Por Aceptar", selected: false },
  { id: 105, idEtapa: 11, idMarca: 2, text: "Por Arbitar", selected: false },
  { id: 106, idEtapa: 11, idMarca: 2, text: "Por Gestionar", selected: false },
  { id: 107, idEtapa: 11, idMarca: 2, text: "Programado", selected: false },
  { id: 108, idEtapa: 11, idMarca: 2, text: "Rechazado", selected: false },
  { id: 109, idEtapa: 11, idMarca: 2, text: "Resuelto", selected: false },
  { id: 110, idEtapa: 9, idMarca: 2, text: "Notificado", selected: false },
  { id: 111, idEtapa: 10, idMarca: 2, text: "Abonado", selected: false },
  { id: 112, idEtapa: 10, idMarca: 2, text: "Abono Programado", selected: false },
  { id: 113, idEtapa: 10, idMarca: 2, text: "Cerrado", selected: false },
  { id: 114, idEtapa: 10, idMarca: 2, text: "Cierre Programado", selected: false },
  { id: 115, idEtapa: 10, idMarca: 2, text: "Configurado", selected: false },
  { id: 116, idEtapa: 10, idMarca: 2, text: "Evidencia Rechazada", selected: false },
  { id: 117, idEtapa: 10, idMarca: 2, text: "Por Abonar", selected: false },
  { id: 118, idEtapa: 10, idMarca: 2, text: "Por Pre-Arbitrar", selected: false },
  { id: 119, idEtapa: 10, idMarca: 2, text: "Programado", selected: false },
  { id: 120, idEtapa: 10, idMarca: 2, text: "Rechazado", selected: false },
  { id: 133, idEtapa: 10, idMarca: 2, text: "Aceptado", selected: false },
  { id: 134, idEtapa: 10, idMarca: 2, text: "No Gestionado/Aceptado", selected: false },
  { id: 135, idEtapa: 3, idMarca: 1, text: "Configurado", selected: false },
  { id: 136, idEtapa: 5, idMarca: 1, text: "Debito Programado", selected: false },
  { id: 137, idEtapa: 5, idMarca: 1, text: "Debito Programado", selected: false },
  { id: 138, idEtapa: 11, idMarca: 2, text: "Debito Programado", selected: false },
  { id: 139, idEtapa: 11, idMarca: 2, text: "Debito Programado", selected: false },
  { id: 140, idEtapa: 10, idMarca: 2, text: "Reporte descargado", selected: false },
  { id: 141, idEtapa: 4, idMarca: 1, text: "Reporte descargado", selected: false },
  { id: 142, idEtapa: 4, idMarca: 1, text: "Aceptado/Comercio", selected: false },
  { id: 143, idEtapa: 11, idMarca: 2, text: "Aceptado/Comercio", selected: false },
  { id: 144, idEtapa: 11, idMarca: 2, text: "Cierre Programado", selected: false },
  { id: 145, idEtapa: 5, idMarca: 1, text: "Cierre Programado", selected: false },
  { id: 146, idEtapa: 2, idMarca: 1, text: "Aceptado/Comercio", selected: false },
  { id: 147, idEtapa: 9, idMarca: 2, text: "Aceptado/Comercio", selected: false },
  { id: 148, idEtapa: 2, idMarca: 1, text: "Rechazado/Comercio", selected: false },
  { id: 149, idEtapa: 9, idMarca: 2, text: "Rechazado/Comercio", selected: false },
  { id: 150, idEtapa: 5, idMarca: 1, text: "Rechazado/Comercio", selected: false },
  { id: 151, idEtapa: 11, idMarca: 2, text: "Rechazado/Comercio", selected: false },
  { id: 152, idEtapa: 3, idMarca: 1, text: "Rechazado/Comercio", selected: false },
  { id: 153, idEtapa: 3, idMarca: 1, text: "Aceptada/Comercio", selected: false },
  { id: 154, idEtapa: 4, idMarca: 1, text: "Rechazado/Comercio", selected: false },
  { id: 155, idEtapa: 10, idMarca: 2, text: "Rechazado/Comercio", selected: false },
  { id: 156, idEtapa: 10, idMarca: 2, text: "Notificado", selected: false },
  { id: 157, idEtapa: 10, idMarca: 2, text: "Aceptado/Comercio", selected: false },
  { id: 158, idEtapa: 10, idMarca: 2, text: "Por Aceptar", selected: false },
  { id: 159, idEtapa: 3, idMarca: 1, text: "Previo Por Aceptar", selected: false },
  { id: 160, idEtapa: 3, idMarca: 1, text: "Por Aceptar", selected: false },
  { id: 161, idEtapa: 3, idMarca: 1, text: "Aceptado", selected: false },

];


export const marcaMap: { [id: number]: string } = {};
MARCAS.forEach(marca => {
  marcaMap[marca.id] = marca.text;
});

export const etapaMap: { [id: number]: string } = {};
ETAPAS.forEach(etapa => {
  etapaMap[etapa.id] = etapa.text;
});

ESTADOS.forEach((estado) => {
  const marcaStr = marcaMap[estado.idMarca];
  const etapaStr = etapaMap[estado.idEtapa];
  estado.visibleText = `${marcaStr} - ${etapaStr} - ${estado.text}`;
});

ETAPAS.forEach((etapa) => {
  const marcaStr = marcaMap[etapa.idMarca];
  etapa.visibleText = `${marcaStr} - ${etapa.text}`;
});